registration:
  path: /register
  controller: App\Controller\RegistrationController:registerAction
  methods: [POST]
app_registration:
  path: /registration
  controller: App\Controller\RegistrationController:registerIndex
app_login:
  path: /
  controller: App\Controller\LoginController:login